-- Raghad Beauty: launch content. Product facts come from the supplied product images.
-- Prices, the WhatsApp number, the Bit number and delivery regions are entered in the admin.

insert into public.site_content (key, value) values
  ('settings', '{"storeName":"Raghad Beauty","storeNameAr":"رغد بيوتي","tagline":"عناية الشعر، مختارة بعناية لكل نوع شعر.","currency":"₪","locale":"ar","dir":"rtl","accent":"#b4125f","ink":"#26102b","paper":"#fbf7fa","whatsapp":"","phone":"","email":"","address":"","orderNote":"الدفع نقدا أو عبر Bit. تؤكد رغد الطلب معك على واتساب.","deliveryNote":"التوصيل متاح حاليا لمنطقة الشمال.","seoTitle":"Raghad Beauty - منتجات سكالا للعناية بالشعر","seoDescription":"كريمات وماسكات سكالا الأصلية للعناية بالشعر مع توصيل لمنطقة الشمال."}'::jsonb),
  ('hero', '{"visible":true,"title":"لكل خصلة عنايتها","text":"كريمات وماسكات Skala لكل أنواع الشعر. اختاري نوع شعرك ونحن نرشح لك الأنسب.","cta":"تسوقي كل المنتجات","autoplay":true}'::jsonb),
  ('copy', '{"catalogTitle":"اختاري ما يناسب شعرك","catalogText":"حددي نوع شعرك وما يحتاجه، وستظهر لك المنتجات المناسبة فقط.","howTitle":"عبوة واحدة، أكثر من استخدام","howText":"معظم كريمات سكالا تستخدم بأكثر من طريقة. طريقة كل منتج مذكورة في صفحته.","reviewsTitle":"تجارب الزبونات","reviewsText":"شاركينا تجربتك وصورة النتيجة. تظهر التقييمات بعد مراجعتها.","contactTitle":"محتارة أي منتج يناسبك؟","contactText":"راسلي رغد على واتساب وصفي لها شعرك، وهي تساعدك في الاختيار."}'::jsonb),
  ('footer', '{"about":"متجر رغد لمنتجات العناية بالشعر. منتجات أصلية، نصيحة صادقة، وتوصيل لباب البيت.","rights":"جميع الحقوق محفوظة","creditLabel":"تصميم وتطوير","creditName":"Darb","creditUrl":"https://darb.co.il"}'::jsonb),
  ('labels', '{"textures":{"light":"خفيف","medium":"وسط","medium-heavy":"وسط لثقيل","heavy":"ثقيل"},"usages":{"mask":"ماسك","leavein":"ليف إن","cowash":"كوواش","cream":"كريم"}}'::jsonb);

insert into public.brands (id, name, name_ar, origin, visible, sort_order) values
  ('skala', 'Skala', 'سكالا', 'البرازيل', true, 0);

insert into public.categories (id, name, visible, sort_order) values
  ('hair-cream', 'كريمات وماسكات الشعر', true, 0),
  ('hair-oil', 'زيوت الشعر', false, 1),
  ('skin', 'العناية بالبشرة', false, 2);

insert into public.needs (id, name, icon, sort_order) values
  ('hydration', 'ترطيب', 'drop', 0),
  ('protein', 'بروتين', 'bond', 1),
  ('nourish', 'تغذية', 'leaf', 2);

insert into public.hair_types (id, name, curl, sort_order) values
  ('straight', 'ناعم', 0.08, 0),
  ('wavy', 'ويفي', 0.42, 1),
  ('curly', 'كيرلي', 0.78, 2),
  ('coily', 'أفريقي', 1, 3);

insert into public.products (id, brand, category, line, name, name_ar, summary, benefits, actives, need, hair, texture, usage, size, price, img, thumb, bg, r1, r2, available, visible, featured, family, source_note, sort_order) values
  ('mais-crespos', 'skala', 'hair-cream', 'Expert', 'Mais Crespos', 'ميس كريسبوس', 'ترطيب عميق وفك للتشابك مع تغذية للشعر.', array['يعمل على الترطيب العميق وفك التشابك وتغذية الشعر','خلطة زيوت أمازونية وأحماض أمينية','سهلة الاختراق لحراشف الشعرة']::text[], 'مكونات بروتين وزيوت ترطيب', array['nourish']::text[], array['curly','coily']::text[], 'medium-heavy', array['mask','leavein','cowash']::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-crespos.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-crespos-s.webp', '#d8a371', '#f08a1c', '#8a3fb0', true, true, true, false, '', 0),
  ('babosa', 'skala', 'hair-cream', 'Expert', 'Babosa', 'بابوزا', 'يمنح الشعر مزيدا من النعومة واللمعان.', array['يعمل على منح الشعر مزيدا من النعومة واللمعان']::text[], 'زيت جوز الهند، الألوفيرا', array['hydration']::text[], array['curly','wavy','straight']::text[], 'medium', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/babosa.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/babosa-s.webp', '#bd6349', '#7fd3c4', '#2e8b3d', true, true, true, false, '', 1),
  ('amor', 'skala', 'hair-cream', 'Expert', 'Potão do Amor', 'لوف بوت', 'صمم للشعر المتضرر والمصبوغ والمتعرض للحرارة.', array['صمم للشعر المتضرر والمصبوغ والمتعرض للحرارة']::text[], '5 مكونات بروتين', array['protein']::text[], array['wavy','curly']::text[], 'heavy', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/amor.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/amor-s.webp', '#137c80', '#e2332f', '#f2c230', true, true, true, false, '', 2),
  ('mais-lisos', 'skala', 'hair-cream', 'Expert', 'Mais Lisos', 'ميس ليسوس', 'يعوض نقص البروتين ويقلل هيشان الشعر.', array['يعوض نقص البروتين','يقلل هيشان الشعر','يعالج ضرر وضعف الشعر','إعادة بناء الشعرة من الداخل']::text[], '', array['protein']::text[], array['straight']::text[], '', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-lisos.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-lisos-s.webp', '#dbccd2', '#7b2fa0', '#c6d936', true, true, true, false, 'نوع الشعر مأخوذ من نص العبوة (للشعر الأملس). القوام والمواد الفعالة غير مذكورة في الصورة.', 3),
  ('manga', 'skala', 'hair-cream', 'Brasil', 'Manga e Castanha-do-Pará', 'المانجا', 'يرطب الشعر بعمق ويقلل الهيشان.', array['يعمل على ترطيب الشعر بعمق ويقلل هيشان الشعر']::text[], 'زبدة المانجا، زبدة الشيا، زبدة الكاجو', array['hydration']::text[], array['wavy','curly','straight']::text[], 'light', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/manga.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/manga-s.webp', '#a3b346', '#f28a1e', '#d2362b', true, true, true, false, 'الصورة تذكر "زبدة الكاجو" بينما العبوة تذكر Castanha-do-Pará. يحتاج تأكيد.', 4),
  ('dona', 'skala', 'hair-cream', 'Expert', 'Dona Skala', 'دونا سكالا', 'رطوبة عميقة للشعر المتضرر وإعادة لمعانه.', array['يقوي الشعرة','يرطب الشعر','رطوبة عميقة للشعر المتضرر','إعادة لمعانه']::text[], '', array['hydration']::text[], array['straight','wavy']::text[], '', array['mask','leavein','cowash']::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/dona.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/dona-s.webp', '#e7b3c0', '#b23a6e', '#6fa84f', true, true, true, false, 'نوع الشعر مأخوذ من نص العبوة (أملس ومموج). القوام غير مذكور.', 5),
  ('12em1', 'skala', 'hair-cream', '', '12 em 1', 'ماسك البروتين 12 في 1', 'يكافح كافة أشكال الضرر مثل التقصف وضعف الشعر.', array['يعمل على مكافحة كافة أشكال الضرر مثل التقصف وضعف الشعر','مناسب لجميع أنواع المساميات']::text[], '', array['protein']::text[], array['all']::text[], '', array['mask','cowash']::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/12em1.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/12em1-s.webp', '#f9b0cd', '#a3183f', '#d4af37', true, true, false, false, 'القوام والمواد الفعالة غير مذكورة في الصورة.', 6),
  ('genetiqs', 'skala', 'hair-cream', '', 'Genetiqs', 'ماسك الترطيب جينيتكس', 'يعالج الشعر التالف والباهت ويمنحه لمعانا.', array['يعمل على معالجة الشعر التالف والباهت ويمنحه لمعانا','مناسب لجميع أنواع المساميات']::text[], '', array['hydration']::text[], array['all']::text[], '', array['mask','cowash']::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/genetiqs.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/genetiqs-s.webp', '#91a6e7', '#8e2a86', '#d9b54a', true, true, false, false, 'القوام والمواد الفعالة غير مذكورة في الصورة.', 7),
  ('mais-cachos', 'skala', 'hair-cream', 'Brasil', 'Mais Cachos', 'ميس كاشوس', 'تحديد خصل الشعر بشكل واضح وبدون نفشة.', array['تحديد خصل الشعر بشكل واضح وبدون نفشة','مناسب للمسامية المنخفضة وجميع المساميات']::text[], '', array['hydration']::text[], array['curly']::text[], '', array['cream','mask']::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-cachos.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-cachos-s.webp', '#e1a090', '#4a9fd6', '#f2c230', true, true, false, false, 'الصورة لقطة شاشة من ستوري. نوع الشعر مأخوذ من نص العبوة (لكل أنواع الكيرلي). القوام غير مذكور.', 8),
  ('cacau', 'skala', 'hair-cream', 'Brasil', 'Cacau', 'كريم الكاكاو', 'تركيبة حصرية بالزيوت الحيوية العضوية للشعر الجاف.', array['للشعر الجاف ذو الأطراف الجافة','تركيبة حصرية بالزيوت الحيوية العضوية','مناسب لجميع أنواع المساميات']::text[], 'زيوت حيوية عضوية', array['hydration']::text[], array['all']::text[], '', array['mask','cowash']::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/cacau.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/cacau-s.webp', '#feb9be', '#c7375e', '#f0b23a', true, true, false, false, 'نوع المنتج (ترطيب) مأخوذ من نص العبوة Hidratação. القوام غير مذكور.', 9),
  ('abacate', 'skala', 'hair-cream', 'Expert', 'Abacate', 'الأفوكادو', 'ترطيب وحيوية للشعر بخلاصة زيت الأفوكادو.', array['يعمل على ترطيب وحيوية الشعر']::text[], 'خلاصة زيت الأفوكادو', array['hydration']::text[], array['all']::text[], 'medium', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/abacate.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/abacate-s.webp', '#b1b384', '#2f3326', '#c9d24a', true, true, false, false, '', 10),
  ('biotina', 'skala', 'hair-cream', 'Expert', 'Bomba de Biotina', 'ماسك التغذية بيوتين', 'ماسك تغذية للشعر الجاف ذو الأطراف الجافة.', array['للشعر الجاف ذو الأطراف الجافة','يحتوي على تركيبة حصرية بالزيوت الحيوية العضوية','مناسب لجميع أنواع المساميات']::text[], 'زيوت حيوية عضوية', array['nourish']::text[], array['all']::text[], '', array['mask','cowash']::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/biotina.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/biotina-s.webp', '#d8bbfe', '#b9774f', '#f1d6c2', true, true, false, false, 'القوام غير مذكور في الصورة.', 11),
  ('vinagre', 'skala', 'hair-cream', 'Expert', 'Vinagre de Maçã', 'خل التفاح', 'يرمم الشعر المتضرر ويقلل من هيشان الشعر.', array['يعمل على ترميم الشعر المتضرر ويقلل من هيشان الشعر']::text[], 'مكونات بروتينية', array['protein']::text[], array['all']::text[], 'medium', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/vinagre.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/vinagre-s.webp', '#d5beb0', '#b23a2e', '#5f8f5a', true, true, false, false, '', 12),
  ('divino-potao', 'skala', 'hair-cream', 'Expert', 'Divino Potão', 'ديفينو بوتاو', 'يساعد على تحديد شكل الخصل ويرمم الشعر المتضرر.', array['غني بالكيراتين النباتي والكولاجين النباتي','يساعد على تحديد شكل الخصل','يرمم الشعر المتضرر']::text[], 'كيراتين نباتي، كولاجين نباتي', '{}'::text[], array['curly','wavy']::text[], '', array['mask','cream','cowash']::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/divino-potao.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/divino-potao-s.webp', '#f9b0cd', '#c2298f', '#3fb7ac', true, true, false, false, 'نوع المنتج (ترطيب / بروتين / تغذية) والقوام غير مذكورين في الصورة.', 13),
  ('divino-potinho', 'skala', 'hair-cream', 'Expert', 'Divino Potinho Kids', 'ديفينو بوتينهو للأطفال', 'يفك التشابك ويسهل تمشيط الشعر.', array['يعمل على فك التشابك ويسهل تمشيط الشعر']::text[], 'بروتينات وزيوت ترطيبية', array['hydration','nourish']::text[], array['curly']::text[], 'heavy', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/divino-potinho.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/divino-potinho-s.webp', '#cb848c', '#ee3f7d', '#f6c21c', true, true, false, true, '', 14),
  ('banana', 'skala', 'hair-cream', 'Brasil', 'Banana e Bacuri', 'الموز', 'يقوي روابط الشعر ويعزز نموه.', array['يعمل على تقوية روابط الشعر وتعزيز نموه']::text[], 'مستخلص فواكه الموز، زبدة الباكوري', array['nourish']::text[], array['wavy','curly','straight']::text[], 'light', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/banana.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/banana-s.webp', '#bad0c4', '#e2b91f', '#3f8f3a', true, true, false, false, 'سطر القوام مقصوص جزئيا في الصورة وقرئ على أنه "خفيف". يحتاج تأكيد.', 15),
  ('mais-crespinhos', 'skala', 'hair-cream', 'Expert', 'Mais Crespinhos', 'ميس كريسبنهوس', 'يعزز إصلاح الشعر ويرطبه ويغذيه.', array['مناسب للشباب','يعزز إصلاح الشعر ويرطبه ويغذيه']::text[], 'زيت الأرجان، زيت جوز الهند، بذور الكتان', array['hydration']::text[], array['curly']::text[], 'medium', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-crespinhos.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-crespinhos-s.webp', '#172b46', '#58b3e6', '#e23a2e', true, true, false, true, '', 16),
  ('amido', 'skala', 'hair-cream', 'Expert', 'Amido de Milho', 'أميدو دي ميلو', 'يقلل هيشان الشعر ويرطبه.', array['يعمل على تقليل هيشان الشعر ويرطب الشعر']::text[], 'نشا الذرة، د-بانثينول', array['hydration']::text[], array['all']::text[], 'medium', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/amido.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/amido-s.webp', '#77c3dd', '#f2c81e', '#2aa39a', true, true, false, false, '', 17),
  ('mais-cachinhos', 'skala', 'hair-cream', 'Expert', 'Mais Cachinhos', 'ميس كاشينهوز', 'يحبس رطوبة مضاعفة ويفك التشابك.', array['يعمل على حبس رطوبة مضاعف وفك التشابك']::text[], 'الألوفيرا، د-بانثينول، زبدة الشيا', array['hydration']::text[], array['curly','wavy']::text[], 'medium', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-cachinhos.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/mais-cachinhos-s.webp', '#e4bbb5', '#8a3fb5', '#52c4e8', true, true, false, true, '', 18),
  ('divina-cor', 'skala', 'hair-cream', 'Expert', 'Divina Cor', 'ديفينا كور', 'يعالج الشعر المتضرر من العلاجات الكيميائية.', array['يعمل على معالجة الشعر المتضرر من العلاجات الكيميائية']::text[], 'مكونات بروتين', array['protein']::text[], array['curly','wavy']::text[], 'medium', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/divina-cor.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/divina-cor-s.webp', '#a34b7d', '#b6d433', '#e63fa0', true, true, false, false, '', 19),
  ('maionese', 'skala', 'hair-cream', 'Expert', 'Maionese Capilar', 'المايونيز', 'يحفز البصيلات ويوازن نسبة الرطوبة ويمنع التقصف.', array['يعمل على تحفيز البصيلات وموازنة نسبة الرطوبة ومنع التقصف']::text[], '3 مكونات بروتين', array['nourish']::text[], array['wavy','curly']::text[], 'heavy', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/maionese.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/maionese-s.webp', '#04284c', '#f1e3b0', '#f09a1e', true, true, false, false, '', 20),
  ('desmaiado', 'skala', 'hair-cream', 'Expert', 'Potão Desmaiado', 'بوتاو ديسميادو', 'ماسك لعلاج الشعر المتضرر ووقاية للشعر الصحي.', array['ماسك لعلاج الشعر المتضرر ووقاية للشعر الصحي']::text[], 'زيت جوز الهند، زيت الخروع، زبدة الشيا', array['hydration']::text[], array['wavy','curly']::text[], 'light', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/desmaiado.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/desmaiado-s.webp', '#2a2030', '#bfe6dc', '#6a3fb0', true, true, false, false, '', 21),
  ('coquetel', 'skala', 'hair-cream', 'Expert', 'Coquetel de Frutas Family', 'كوكتيل الفواكه للعائلة', 'للتصفيف اليومي، للصغار والكبار.', array['للصغار والكبار','التصفيف اليومي','ترطيب الشعر','تقليل هيشان الشعر','غني بفيتامينات A, B, C']::text[], 'فيتامينات A, B, C', array['hydration']::text[], array['all']::text[], '', '{}'::text[], '1000g', null, 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/coquetel.webp', 'https://bvmtbmpjppangdqjdvpx.supabase.co/storage/v1/object/public/media/jars/coquetel-s.webp', '#f4a9b8', '#f6e36a', '#7fcfe6', true, true, false, true, 'نوع الشعر مأخوذ من نص العبوة (لكل أنواع الشعر). القوام غير مذكور.', 22);

insert into public.payments (id, name, number, note, active, sort_order) values
  ('cash', 'نقدا', '', 'تدفعين نقدا عند استلام الطلب.', true, 0),
  ('bit', 'Bit', '', 'بعد أن تؤكد رغد الطلب، حولي المبلغ عبر تطبيق Bit إلى هذا الرقم.', true, 1);

insert into public.promos (id, text, code, visible, sort_order) values
  ('pr2', 'توصيل لمنطقة الشمال - الدفع نقدا أو عبر Bit', '', true, 0);

insert into public.usage_guide (id, title, text, sort_order) values
  ('mask', 'ماسك', 'يوزع على الشعر بعد الغسل ويترك بعض الوقت ثم يشطف.', 0),
  ('leavein', 'ليف إن', 'كمية صغيرة على الشعر الرطب تترك دون شطف للتصفيف.', 1),
  ('cowash', 'كوواش', 'غسل الشعر بالكريم بدلا من الشامبو.', 2),
  ('cream', 'كريم تصفيف', 'يستخدم لتحديد الخصل وتصفيف الشعر.', 3);

insert into public.sections (id, title, visible, sort_order) values
  ('hero', 'الواجهة الرئيسية', true, 0),
  ('promo', 'شريط العروض', true, 1),
  ('catalog', 'المنتجات ومرشد الشعر', true, 2),
  ('how', 'طرق الاستخدام', true, 3),
  ('reviews', 'تجارب الزبونات', true, 4),
  ('contact', 'التواصل', true, 5);

insert into public.nav_links (id, label, target, visible, sort_order) values
  ('n1', 'المنتجات', '#catalog', true, 0),
  ('n2', 'طرق الاستخدام', '#how', true, 1),
  ('n3', 'التقييمات', '#reviews', true, 2),
  ('n4', 'تواصلي معنا', '#contact', true, 3);

-- First admin (the auth user is created separately; this only grants access).
insert into private.admin_users (user_id)
select id from auth.users where email = 'raghad@darb.co.il'
on conflict do nothing;
